### ISSUE TITLE
buildnml won't allow nemsio files

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/FV3GFS_interface#4]
If I try to put nemsio files in the DIN_LOC_IC directory the buildnml still lists the ic_grib2 file in the download list.

**Comment by uturuncoglu** [comment]
Yes. To test it, i created new data directory and put nemsio file in it (tmp dir has grib2)

./xmlchange RUN_STARTDATE=2019-12-24
./xmlchange START_TOD=43200

Then preview namelist works without any problem but ./case.submit tries to download grib2. I'll fix buildnml and let you know.

**Comment by uturuncoglu** [comment]
Okay. I fixed it it is in the our release branch https://github.com/ESCOMP/FV3GFS_interface/commit/f0b5883a1d0fc86cad0bc4b1cad215c99f0d5263. The behavior is

- if there is no data for specified date, it tries to download grib2
- if both nemsio and grib2 are in the input directory, grib2 is processed
- if nemsio is in the folder, it process it and does not try to download grib2
